var gameMode=1,autoShoot=0,bubbleWeight=1,bubbleSpeed=1.5,bubbleRadius=5,maxBubbleWeight=15,bubbleFrequency=150,combineBubbleMode=0,canvasX=320,canvasY=480,msPerRender=4,game,canvas,input,t,song,debugOut;function main(){debugOut=document.getElementById("test");flushGame();game=new Game;game.create();canvas=new Canvas;canvas.create();input=new Input;input.create();t=setTimeout(redraw,1)}function redraw(){canvas.redraw();t=setTimeout(redraw,1)}function flushGame(){}
function musicToggle(){var a=document.getElementById("musicToggle");0===parseInt(a.getAttribute("playing"))?(song.play(),a.setAttribute("playing",1),a.innerHTML="<p>Music<br />On</p>"):1===parseInt(a.getAttribute("playing"))&&(song.pause(),song.currentTime=0,a.setAttribute("playing",0),a.innerHTML="<p>Music<br />Off</p>")}function Game(){this.blocks;this.bubbles}Game.prototype.create=function(){this.blocks=[];this.bubbles=[];this.asplodeBubbles=[];this.load()};
Game.prototype.load=function(){"Microsoft Internet Explorer"!=navigator.appname&&(song=new Audio("6-1-12.ogg"),song.loop=!0,document.getElementById("musicToggle").addEventListener("click",musicToggle,!1));this.blocks[0]=new Block;this.blocks[0].create(200,200,100,10);this.blocks[1]=new Block;this.blocks[1].create(50,100,50,10)};Game.prototype.destruct=function(){alert("Game restarted, too many damn bubbles.");clearTimeout(t);this.create()};function Canvas(){this.ctx;this.calcCount}
Canvas.prototype.create=function(){this.ctx=document.getElementById("canvas").getContext("2d");this.calcCount=0;this.redraw()};
Canvas.prototype.redraw=function(){for(var a in game.bubbles)game.bubbles[a]&&game.bubbles[a].calculate();this.calcCount++;if(this.calcCount===msPerRender){this.ctx.clearRect(0,0,canvasX,canvasY);for(a in game.blocks)game.blocks[a]&&game.blocks[a].redraw();for(a in game.bubbles)game.bubbles[a]&&game.bubbles[a].redraw();for(a in game.asplodeBubbles)game.asplodeBubbles[a]&&game.asplodeBubbles[a].asplode();this.calcCount=0}};function Input(){this.t;this.held;this.x;this.y}
Input.prototype.create=function(){this.held=!1;document.getElementById("canvas").addEventListener("mousedown",function(a){input.down(a)},!1);document.getElementById("canvas").addEventListener("mousemove",function(a){input.move(a)},!1);document.getElementById("canvas").addEventListener("mouseup",function(a){input.up(a)},!1)};Input.prototype.down=function(a){this.held=!0;this.x=a.pageX;this.y=a.pageY;createBubble(this.x,this.y);this.t=setTimeout(function(){input.hold()},500)};
Input.prototype.move=function(a){!0===this.held&&(this.x=a.pageX,this.y=a.pageY)};Input.prototype.up=function(){this.held=!1;clearTimeout(this.t)};Input.prototype.hold=function(){!0===this.held&&(createBubble(this.x,this.y),this.t=setTimeout(function(){input.hold()},bubbleFrequency))};
function createBubble(a,b){1===autoShoot&&setTimeout(createBubble,bubbleFrequency/2,41+Math.random()*(canvasX-41),Math.random()*canvasY);var c=new Bubble;c.create(a,b);41<=b&&(c.index=game.bubbles.length,game.bubbles[c.index]=c);debugOut.innerHTML=c.index}function Bubble(){this.type;this.index;this.isBlocked;this.x;this.y;this.r;this.weight;this.moving;this.asploding}
Bubble.prototype.create=function(a,b){this.type="Bubble";this.x=a;this.y=b;this.r;this.weight=bubbleWeight<=maxBubbleWeight-1||0===maxBubbleWeight?bubbleWeight:maxBubbleWeight-1;this.moving=!0;this.asploding=!1};
Bubble.prototype.calculate=function(){for(var a in game.bubbles)game.bubbles[a]&&a!=this.index&&this.combine(game.bubbles[a]);this.r=Math.sqrt(Math.pow(bubbleRadius,2)*this.weight);var b=!1,c={x:this.x,y:this.y,r:this.r};for(a in game.blocks)game.blocks[a].position(this.type,c)&&(this.x=game.blocks[a].position(this.type,c)[0],this.y=game.blocks[a].position(this.type,c)[1],this.moving=!1,b=!0);!1===b&&(this.y-=bubbleSpeed,this.moving=!0);(this.y<=10+30*Math.random()||1<=maxBubbleWeight&&this.weight>=
maxBubbleWeight)&&this.asplodePrepare()};Bubble.prototype.combine=function(a){if(this.weight<=a.weight&&Math.sqrt(Math.pow(this.x-a.x,2)+Math.pow(this.y-a.y,2))<=this.r+a.r){var b=a.weight;a.weight+=this.weight;a.y+=Math.sqrt(Math.pow(bubbleRadius,2)*this.weight);a.x=0===combineBubbleMode?(this.x*this.weight+a.x*b)/(this.weight+b):this.x;this.destruct();a.redraw()}};
Bubble.prototype.redraw=function(){canvas.ctx.beginPath();canvas.ctx.strokeStyle="LightSeaGreen";canvas.ctx.arc(this.moving?this.x+Math.sqrt(this.r)/2-Math.random()*Math.sqrt(this.r):this.x,this.y,this.r,0,2*Math.PI);canvas.ctx.stroke();canvas.ctx.fillStyle="LightSeaGreen";canvas.ctx.font="10px Tahoma, Geneva, sans-serif";canvas.ctx.textAlign="center";canvas.ctx.textBaseline="middle";canvas.ctx.fillText(Math.floor(this.weight),this.x,this.y)};
Bubble.prototype.asplodePrepare=function(){this.d=0;this.rStart=this.r*=2;this.y+=this.r/4;var a=game.asplodeBubbles.length;this.destruct();this.index=a;this.asploding=!0;game.asplodeBubbles[a]=this};
Bubble.prototype.asplode=function(){this.r>=this.rStart/15?(this.d+=0.1,this.r-=this.rStart/30,this.y-=this.rStart/30,canvas.ctx.beginPath(),canvas.ctx.strokeStyle="LightSkyBlue",canvas.ctx.arc(this.x+Math.sqrt(this.r)-2*Math.random()*Math.sqrt(this.r),this.y,this.r,1.5*Math.PI-this.d-1*Math.random(),1.5*Math.PI+this.d+1*Math.random(),!0),canvas.ctx.stroke(),canvas.ctx.beginPath(),canvas.ctx.strokeStyle="PowderBlue",canvas.ctx.arc(this.x,this.y,0<=this.r-3?this.r-3:0,1.5*Math.PI-this.d,1.5*Math.PI+
this.d,!0),canvas.ctx.stroke(),canvas.ctx.beginPath(),canvas.ctx.strokeStyle="White",canvas.ctx.arc(this.x,this.y,this.r,1.5*Math.PI+this.d,1.5*Math.PI-this.d,!0),canvas.ctx.stroke()):this.destruct()};Bubble.prototype.destruct=function(){game.bubbles[this.index]&&!1===this.asploding&&(game.bubbles[this.index]=null);game.asplodeBubbles[this.index]&&!0===this.asploding&&(game.asplodeBubbles[this.index]=null)};function Block(){this.type;this.index;this.x;this.y;this.w;this.h}
Block.prototype.create=function(a,b,c,d){this.type="Block";this.x=a;this.y=b;this.w=c;this.h=d};Block.prototype.redraw=function(){canvas.ctx.beginPath();canvas.ctx.strokeStyle="Black";canvas.ctx.strokeRect(this.x,this.y,this.w,this.h);canvas.ctx.stroke()};Block.prototype.position=function(a,b){if("Bubble"===a){var c=b.x,d=b.y,e=b.r;return c>=this.x&&c<=this.x+this.w&&d>=this.y+this.h+e&&d<=this.y+this.h+e+2?[c,d]:!1}return!1};
function FloatBlock(){this.type;this.index;this.x;this.y;this.w;this.h;this.weight}FloatBlock.prototype.create=function(a,b,c,d){this.type="FloatBlock";this.x=a;this.y=b;this.w=c;this.h=d};FloatBlock.prototype.redraw=function(){canvas.ctx.beginPath();canvas.ctx.strokeStyle="Black";canvas.ctx.strokeRect(this.x,this.y,this.w,this.h);canvas.ctx.stroke()};FloatBlock.prototype.position=function(a,b,c){return a>=this.x&&a<=this.x+this.w&&b>=this.y+this.h+c&&b<=this.y+this.h+c+2?[a,b]:!1};